module ppt2

using LinearAlgebra
using JuMP
using MosekTools
using DynamicPolynomials
using SumOfSquares

export gen_pncp, poly2mat, apply_map

"""
    step1_1(n::Int, m::Int) -> Tuple

Generates random points on the Segre variety.

Inputs:
    n, m [Int] - size of the problem.

Outputs:
    X [Matrix] - n x (e+1) random points
    Y [Matrix] - m x (e+1) random points
    Z [Matrix] - nm x (e+1) Kronecker products of X and Y

The matrix Z stores all the points zi, formed from the
kronecker products of xi and yi.
"""
function step1_1(n::Int, m::Int)
    e = (n - 1) * (m - 1)
    X = randn(n, e + 1)
    Y = randn(m, e + 1)
    Z = zeros(n * m, e + 1)

    for i in 1:e+1
        Z[:, i] = kron(X[:, i], Y[:, i])
    end

    return Z
end

"""
    step1_2(n::Int, m::Int, Z::Matrix) -> Matrix

Generates the linear forms h1, ..., hd

Inputs:
    n, m [Int] - size of the problem.
    Z [Matrix] - random points on the Segre variety as column vectors.
                 The size of Z is needed to be (n*m, (n-1)*(m-1)+1).

Outputs:
    V [Matrix] - random vectors from the kernel of Z' as columns.

If the size of the input matrix Z is incorrect the function stops.
"""
function step1_2(n::Int, m::Int, Z::Matrix)
    d = n + m - 2

    # Generate random linear forms from kernel
    ker = nullspace(Z')
    V = ker * randn(size(ker, 2), d)

    return V
end

"""
    step1_3(n::Int, m::Int, Z::Matrix) -> Vector

Computes the linear form h_0

Inputs:
    Z [Matrix] - random points Z_i on the Segre variety as column vectors.
                 NOTE: Z should be the matrix generated by step1_1

Outputs:
    v0 [Vector] - Random vector from the kernel of Z(:, 1:end-1).
                  v0 defines the linear form h_0.
"""
function step1_3(Z::Matrix)
    # Choose random vector v0 from kernel
    ker = nullspace(Z[:, 1:end - 1]')
    v0 = ker * randn(size(ker, 2), 1)

    return v0
end

"""
    step2_1(n::Int, m::Int, Z::Matrix) -> Vector{Matrix}

Computes a basis of kernels of the generators of the Segre variety.

Inputs:
    n, m [Int] - size of the problem.
    Z [Matrix] - random points Z_i on the Segre variety as column vectors.

Outputs:
    W [Vector] - basis of the kernels for each point Z_i.

We loop through the rows and columns. For each 2x2 minor created in this
way, we store the derivative of the minor in a vector to create the
gradient vector of the generators.
"""
function step2_1(n::Int, m::Int, Z::Matrix)
    e = (n - 1) * (m - 1)
    W = Vector{Matrix{Float64}}(undef, e)

    for col = 1:e
        G = zeros(n*m, n*m*e÷4)
        idx = 0
        for i = 1:n-1, k = i+1:n
            for j = 1:m-1, l = j+1:m
                idx += 1
                g = zeros(n * m)
                ij = m * (i - 1) + j
                kl = m * (k - 1) + l
                il = m * (i - 1) + l
                kj = m * (k - 1) + j
                z = Z[:, col]
                g[kl] =  z[ij]
                g[kj] = -z[il]
                g[ij] =  z[kl]
                g[il] = -z[kj]
                G[:, idx] = g
            end
        end
        W[col] = nullspace(G')
    end

    return W
end

"""
    step2_2(n::Int, m::Int, Z::Matrix, W::Vector, v0::Vector, V::Matrix) -> Vector

Finds the vector v that represents 'f'

Inputs:
    n, m [Int] - size of the problem.
    Z [Matrix] - random points on Segre variety (from step1_1)
    W [Vector] - basis of kernels (from step2_1)
    V [Matrix] - linear forms h_0,...,h_d (from step1_2 & step1_3)

Outputs:
    v [Vector] - quadratic form 'f' which is not a sum of squares on the Segre variety.
"""
function step2_2(n::Int, m::Int, Z::Matrix, W::Vector, V::Matrix)
    e = (n - 1) * (m - 1)
    d = n + m - 1
    nm = n * m

    I_n = Matrix{Float64}(I, n, n)
    I_m = Matrix{Float64}(I, m, m)
    I_nm = Matrix{Float64}(I, nm, nm)

    function E(i, j, k, l)
        e_ij = kron(I_n[:, i], I_m[:, j])
        e_kl = kron(I_n[:, k], I_m[:, l])
        return kron(e_ij, e_kl) + kron(e_kl, e_ij)
    end

    matrices = zeros(e*d+nm*(nm-1)÷2, nm^2)
    row = 1

    for i = 1:e
        for j = 1:d
            matrices[row, :] = kron(Z[:, i], W[i][:, j])'
            row += 1
        end
    end

    for i = 1:nm-1
        for j = i+1:nm
            matrices[row, :] = kron(I_nm[:, i], I_nm[:, j])' - kron(I_nm[:, j], I_nm[:, i])'
            row += 1
        end
    end

    span = zeros(Float64, nm^2, nm*e÷4+d^2)
    col = 1

    for i = 1:n-1
        for k = i+1:n
            for j = 1:m-1
                for l = j+1:m
                    span[:, col] = E(i, j, k, l) - E(i, l, k, j)
                    col += 1
                end
            end
        end
    end

    for i = 1:d
        for j = 1:d
            span[:, col] = kron(V[:, i], V[:, j]) + kron(V[:, j], V[:, i])
            col += 1
        end
    end

    r = rank(span)
    ker = nullspace(matrices)

    while true
        v = ker * randn(size(ker, 2))
        rank([span v]) > r && return v
    end

    return v
end

"""
    is_sos(n::Int, m::Int, v::Vector, V::Matrix) -> Tuple

Checks if the given form is a sum of squares.

Inputs:
    n, m [Int] - size of the problem.
    v [Vector] - quadratic form
    V [Matrix] - linear forms

Outputs:
    ss [Bool] - Sum of squares flag
    del [Float] - parameter value
"""
function is_sos(n::Int, m::Int, v::Vector, V::Matrix)
    model = SOSModel(Mosek.Optimizer)
    set_silent(model)

    @polyvar X[1:n] Y[1:m]
    @variable(model, delta)

    # Create polynomial expressions
    XY = kron(X, Y)

    # Forms
    f = v' * kron(XY, XY)
    h = V' * XY

    # SOS constraint
    F = delta * f + (h' * h)

    @constraint(model, F in SOSCone())
    @objective(model, Max, delta)

    optimize!(model)

    del = value(delta)
    ss = termination_status(model) == OPTIMAL && del > 1e-5

    return ss, del
end

"""
    step3(n::Int, m::Int, v::Vector, V::Matrix) -> Tuple

Computes a SOS decomposition of the final form

Inputs:
    n, m [Int] - size of the problem.
    v [Vector] - quadratic form 'f' (from step2_2)
    V [Matrix] - linear forms (from step1_2 and step1_3)

Output:
    nng [Int] - Non-negativity flag
    del [Float] - parameter determining the non-negative, non-SOS form
    res [Float] - The residual between SOS decomposition and input
"""
function step3(n::Int, m::Int, v::Vector, V::Matrix)
    model = SOSModel(Mosek.Optimizer)
    set_silent(model)

    @polyvar X[1:m] Y[1:n]
    @variable(model, delta)

    # Create polynomial expressions
    XY = kron(X, Y)

    # Linear and quadratic forms from input
    f = v' * kron(XY, XY)
    h = V' * XY

    # Create NNG/nonSOS form
    poli = delta * f + 10 * (h' * h)

    # SOS relaxation
    relax = poli * (XY' * XY)

    @constraint(model, relax in SOSCone())
    @objective(model, Max, delta)

    optimize!(model)

    del = value(delta)
    nng = termination_status(model) == OPTIMAL && del > 1e-4

    return nng, del
end

"""
    gen_pncp(n::Int, m::Int) -> Tuple

Generate positive maps that are not completely positive.

Inputs:
    n, m [Int] - size of the problem.

Outputs:
    del [Float] - parameter making the map PnCP
    v [Vector] - non-SOS quadratic form
    V [Matrix] - matrix of linear forms

See article - "There are many more positive maps than completely
positive maps" by Klep, McCullough, Sivic, Zalar
"""
function gen_pncp(n::Int, m::Int)
    nng = false
    attempts = 0

    del = NaN
    v = nothing
    V = nothing

    while !nng && attempts < 10
        ss = true
        count = 0

        while ss && count < 10
            # Linear algebra step
            Z = step1_1(n, m)
            V = step1_2(n, m, Z)
            v0 = step1_3(Z)
            V = [v0 V]
            W = step2_1(n, m, Z)
            v = step2_2(n, m, Z, W, V)

            # Check if form is SOS
            ss, _ = is_sos(n, m, v, V)
            count += 1
        end

        # Test non-negativity
        nng, del = step3(n, m, v, V)
        attempts += 1
    end

    return del, v, V
end

function mat2block(M::Matrix, n::Int, m::Int)
    @assert size(M) == (n*m, n*m) "M must be (n*m) x (n*m)"

    C = [zeros(m, m) for _ in 1:n, _ in 1:n]

    for i in 1:n
        for j in 1:n
            k = (i-1)*m+1 : i*m
            l = (j-1)*m+1 : j*m
            C[i, j] = M[k, l]
        end
    end

    return C
end

function block2mat(C::Matrix)
    n = size(C, 1)
    m = size(C[1, 1], 1)

    M = zeros(n*m, n*m)

    for i in 1:n
        for j in 1:n
            k = (i-1)*m+1 : i*m
            l = (j-1)*m+1 : j*m
            M[k, l] = C[i, j]
        end
    end

    return M
end

function poly2mat(form::Vector, n::Int, m::Int)
    d = n * m

    @polyvar X[1:n] Y[1:m]
    XY = kron(X, Y)

    p = form' * kron(XY, XY)

    M = zeros(Float64, d, d)
    for row in 1:d
        for col in row:d
            i = div(row - 1, m) + 1
            j = div(col - 1, m) + 1

            k = mod(row - 1, m) + 1
            l = mod(col - 1, m) + 1

            mon = X[i] * Y[k] * X[j] * Y[l]
            val = DynamicPolynomials.coefficient(p, mon)

            if i != j
                val = val / 2
            end
            if k != l
                val = val / 2
            end

            if row == col
                M[row, col] = val
            else
                M[row, col] = val
                M[col, row] = val
            end
        end
    end
    return M
end

function apply_map(state::Matrix, phi::Matrix, n::Int, m::Int)
    C_state = mat2block(state, n, m)
    C_phi = mat2block(phi, n, m)

    mapped = Array{Matrix{Float64}}(undef, n, n)
    for i=1:n
        for j=1:n
            L = C_state[i, j];
            Lmap = zeros(m, m);
            for k=1:n
                for l=1:n
                    Lmap = Lmap + L[k, l] * C_phi[k, l];
                end
            end
            mapped[i, j] = Lmap;
        end
    end

    return block2mat(mapped)
end

end # module ppt2
