module ppt2

using LinearAlgebra
using JuMP
using MosekTools
using DynamicPolynomials
using SumOfSquares

export gen_pncp

"""
    step1_1(n::Int, m::Int) -> Tuple

Generates random points on the Segre variety.

Inputs:
    n, m [Int] - size of the problem.

Outputs:
    X [Matrix] - n x (e+1) random points
    Y [Matrix] - m x (e+1) random points
    Z [Matrix] - nm x (e+1) Kronecker products of X and Y

The matrix Z stores all the points zi, formed from the
kronecker products of xi and yi.
"""
function step1_1(n::Int, m::Int)
    e = (n - 1) * (m - 1)
    X = randn(n, e + 1)
    Y = randn(m, e + 1)
    Z = zeros(n * m, e + 1)

    for i in 1:e+1
        Z[:, i] = kron(X[:, i], Y[:, i])
    end

    return Z
end

"""
    step1_2(n::Int, m::Int, Z::Matrix) -> Matrix

Generates the linear forms h1, ..., hd

Inputs:
    n, m [Int] - size of the problem.
    Z [Matrix] - random points on the Segre variety as column vectors.
                 The size of Z is needed to be (n*m, (n-1)*(m-1)+1).

Outputs:
    V [Matrix] - random vectors from the kernel of Z' as columns.

If the size of the input matrix Z is incorrect the function stops.
"""
function step1_2(n::Int, m::Int, Z::Matrix)
    d = n + m - 2

    # Generate random linear forms from kernel
    ker = nullspace(Z')
    V = ker * randn(size(ker, 2), d)

    return V
end

"""
    step1_3(n::Int, m::Int, Z::Matrix) -> Vector

Computes the linear form h_0

Inputs:
    Z [Matrix] - random points Z_i on the Segre variety as column vectors.
                 NOTE: Z should be the matrix generated by step1_1

Outputs:
    v0 [Vector] - Random vector from the kernel of Z(:, 1:end-1).
                  v0 defines the linear form h_0.
"""
function step1_3(Z::Matrix)
    # Choose random vector v0 from kernel
    ker = nullspace(Z[:, 1:end - 1]')
    v0 = ker * randn(size(ker, 2), 1)

    return v0
end

"""
    step2_1(n::Int, m::Int, Z::Matrix) -> Vector{Matrix}

Computes a basis of kernels of the generators of the Segre variety.

Inputs:
    n, m [Int] - size of the problem.
    Z [Matrix] - random points Z_i on the Segre variety as column vectors.

Outputs:
    W [Vector] - basis of the kernels for each point Z_i.

We loop through the rows and columns. For each 2x2 minor created in this
way, we store the derivative of the minor in a vector to create the
gradient vector of the generators.
"""
function step2_1(n::Int, m::Int, Z::Matrix)
    e = (n - 1) * (m - 1)
    W = Vector{Matrix{Float64}}(undef, e)

    for col = 1:e
        G = zeros(n*m, n*m*e÷4)
        idx = 0
        for i = 1:n-1, k = i+1:n
            for j = 1:m-1, l = j+1:m
                idx += 1
                g = zeros(n * m)
                ij = m * (i - 1) + j
                kl = m * (k - 1) + l
                il = m * (i - 1) + l
                kj = m * (k - 1) + j
                z = Z[:, col]
                g[kl] =  z[ij]
                g[kj] = -z[il]
                g[ij] =  z[kl]
                g[il] = -z[kj]
                G[:, idx] = g
            end
        end
        W[col] = nullspace(G')
    end

    return W
end

"""
    step2_2(n::Int, m::Int, Z::Matrix, W::Vector, v0::Vector, V::Matrix) -> Vector

Finds the vector v that represents 'f'

Inputs:
    n, m [Int] - size of the problem.
    Z [Matrix] - random points on Segre variety (from step1_1)
    W [Vector] - basis of kernels (from step2_1)
    V [Matrix] - linear forms h_0,...,h_d (from step1_2 & step1_3)

Outputs:
    v [Vector] - quadratic form 'f' which is not a sum of squares on the Segre variety.
"""
function step2_2(n::Int, m::Int, Z::Matrix, W::Vector, V::Matrix)
    e = (n - 1) * (m - 1)
    d = n + m - 2

    I_n = Matrix{Float64}(I, n, n)
    I_m = Matrix{Float64}(I, m, m)
    I_nm = Matrix{Float64}(I, n*m, n*m)

    function E(i, j, k, l)
        kron_ij = kron(I_n[:, i], I_m[:, j])
        kron_kl = kron(I_n[:, k], I_m[:, l])
        return kron(kron_ij, kron_kl) + kron(kron_kl, kron_ij)
    end

    row = 0
    matrices = zeros(e*(d+1)+n*m*(n*m-1)÷2, n*n*m*m)

    for i = 1:e
        for j = 1:d+1
            row += 1
            matrices[row, :] = kron(Z[:, i], W[i][:, j])'
        end
    end

    for i = 1:n*m-1
        for j = i+1:n*m
            row += 1
            matrices[row, :] = kron(I_nm[:, i], I_nm[:, j])' - kron(I_nm[:, j], I_nm[:, i])'
        end
    end

    col = 0
    matspan = zeros(Float64, n*n*m*m, n*m*e÷4+(d+1)^2)

    for i = 1:n-1
        for k = i+1:n
            for j = 1:m-1
                for l = j+1:m
                    col += 1
                    matspan[:, col] = E(i, j, k, l) - E(i, l, k, j)
                end
            end
        end
    end

    for i = 1:d+1
        for j = 1:d+1
            col += 1
            matspan[:, col] = kron(V[:, i], V[:, j]) + kron(V[:, j], V[:, i])
        end
    end

    r = rank(matspan)
    ker = nullspace(matrices)

    while true
        v = ker * randn(size(ker, 2))
        rank([matspan v]) > r && return v
    end

    return v
end

"""
    is_sos(n::Int, m::Int, v::Vector, V::Matrix) -> Tuple

Checks if the given form is a sum of squares.

Inputs:
    n, m [Int] - size of the problem.
    v [Vector] - quadratic form
    V [Matrix] - linear forms

Outputs:
    ss [Bool] - Sum of squares flag
    del [Float] - parameter value
"""
function is_sos(n::Int, m::Int, v::Vector, V::Matrix)
    model = SOSModel(Mosek.Optimizer)
    set_silent(model)

    @polyvar X[1:n] Y[1:m]
    @variable(model, delta)

    # Create polynomial expressions
    XY = kron(X, Y)

    # Forms
    f = v' * kron(XY, XY)
    h = V' * XY

    # SOS constraint
    F = delta * f + (h' * h)

    @constraint(model, F in SOSCone())
    @objective(model, Max, delta)
    optimize!(model)

    del = value(delta)
    ss = termination_status(model) == OPTIMAL && del > 1e-5

    return ss, del
end

"""
    step3(n::Int, m::Int, v::Vector, V::Matrix) -> Tuple

Computes a SOS decomposition of the final form

Inputs:
    n, m [Int] - size of the problem.
    v [Vector] - quadratic form 'f' (from step2_2)
    V [Matrix] - linear forms (from step1_2 and step1_3)

Output:
    nng [Int] - Non-negativity flag
    del [Float] - parameter determining the non-negative, non-SOS form
    res [Float] - The residual between SOS decomposition and input
"""
function step3(n::Int, m::Int, v::Vector, V::Matrix)
    model = SOSModel(Mosek.Optimizer)
    set_silent(model)

    @polyvar X[1:m] Y[1:n]
    @variable(model, delta)

    # Create polynomial expressions
    XY = kron(X, Y)

    # Linear and quadratic forms from input
    f = v' * kron(XY, XY)
    h = V' * XY
    h_sos = h' * h

    # Create NNG/nonSOS form
    poli = delta * f + 10 * h_sos

    # SOS relaxation
    relax = poli * (XY' * XY)

    @constraint(model, relax in SOSCone())
    @objective(model, Max, delta)

    optimize!(model)

    del = value(delta)
    nng = termination_status(model) == OPTIMAL && del > 1e-4

    return nng, del
end

"""
    gen_pncp(n::Int, m::Int) -> Tuple

Generate positive maps that are not completely positive.

Inputs:
    n, m [Int] - size of the problem.

Outputs:
    del [Float] - parameter making the map PnCP
    v [Vector] - non-SOS quadratic form
    V [Matrix] - matrix of linear forms

See article - "There are many more positive maps than completely
positive maps" by Klep, McCullough, Sivic, Zalar
"""
function gen_pncp(n::Int, m::Int)
    nng = false
    attempts = 0

    del = NaN
    v = nothing
    V = nothing

    while !nng && attempts < 10
        ss = true
        count = 0

        while ss && count < 10
            # Linear algebra step
            Z = step1_1(n, m)
            V = step1_2(n, m, Z)
            v0 = step1_3(Z)
            V = [v0 V]
            W = step2_1(n, m, Z)
            v = step2_2(n, m, Z, W, V)

            # Check if form is SOS
            ss, _ = is_sos(n, m, v, V)
            count += 1
        end

        # Test non-negativity
        nng, del = step3(n, m, v, V)
        attempts += 1
    end

    return del, v, V
end

end # module ppt2
